name: Server Deployment (testAction branch)

on:
    push:
        branches:
            - testAction
        paths:
            - "server/**"
jobs:
    server-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: SSH Commands
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  username: ${{ secrets.SSH_USERNAME }}
                  port: ${{ secrets.SSH_PORT }}
                  script_stop: true
                  script: |
                      cd server_meetsin
                      yarn pm2:kill
                      cd ..
                      rm -rf server_meetsin
                      mkdir github
                      cd github
                      git clone https://github.com/FE-Ocean/meetsin.git
                      cd meetsin/server
                      yarn install
                      yarn build
                      yarn start:prod
