name: Server Deployment (testAction branch)

on:
    push:
        branches:
            - testAction
        paths:
            - "server/**"

jobs:
    server-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "yarn"
                  cache-dependency-path: server/yarn.lock

            - name: Install dependencies
              run: yarn install
              working-directory: server

            - name: Create .env file
              run: |
                  echo "MODE=PROD" > .env
                  jq -r 'to_entries | map(select(.key | startswith("PROD_"))) | map("\(.key | ltrimstr("PROD_"))=\(.value|tostring)") | .[]' <<< "$SECRETS_CONTEXT" >> .env
              env:
                  SECRETS_CONTEXT: ${{ toJson(secrets) }}
              working-directory: server

            - name: Build project
              run: yarn build
              working-directory: server

            - name: Copy file via ssh
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  port: ${{ secrets.SSH_PORT }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  source: /home/runner/work/meetsin/meetsin/server/yarn.lock, /home/runner/work/meetsin/meetsin/server/dist
                  target: ${{ secrets.SSH_TARGET }}

            - name: SSH Commands
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  port: ${{ secrets.SSH_PORT }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  script_stop: true
                  script: |
                      cd server_meetsin
                      yarn pm2:kill
                      yarn install
                      yarn start:prod
