name: Server Deployment (develop branch)

on:
    push:
        branches:
            - develop
        paths:
            - "server/**"

jobs:
    server-deploy:
        runs-on: ubuntu-latest
        
        strategy: // 5
          matrix:
            node-version: [18.x]

        steps:
            - name: Node version check
              uses: actions/setup-node@v4
              with: 
                node-version: ${{ matrix.node-version }}
            - name: SSH Commands
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  username: ${{ secrets.SSH_USERNAME }}
                  port: ${{ secrets.SSH_PORT }}
                  script_stop: true
                  script: |
                      node --version
                      cd github/meetsin/server
                      git pull
                      pm2 kill
                      yarn --version
                      yarn install --immutable
                      yarn build
                      pm2 start ./dist/main.js
