name: Server Deployment (develop branch)

on:
    push:
        branches:
            - github-action-test

jobs:
    server-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: SSH Commands
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  username: ${{ secrets.SSH_USERNAME }}
                  port: ${{ secrets.SSH_PORT }}
                  script_stop: true
                  script: |
                      cd github/meetsin/server
                      git pull origin develop
                      pm2 kill
                      yarn install --frozen-lockfile
                      yarn deploy:dev
