name: Server Deployment (develop branch)

on:
    push:
        branches:
            - develop
        paths:
            - "server/**"

jobs:
    server-deploy:
        runs-on: ubuntu-latest
       
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Node version check
              uses: actions/setup-node@v4
              with: 
                node-version: 18
            - run: node --version
            - name: SSH Commands
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
                  username: ${{ secrets.SSH_USERNAME }}
                  port: ${{ secrets.SSH_PORT }}
            - run: pm2 kill && yarn --version && yarn install --frozen-lockfile && yarn build && pm2 start ./dist/main.js
